version: '3.8'

services:
  backend:
    build:
      context: ./server-backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./server-backend:/app
      - /app/node_modules

  frontend:
    build:
      context: .
      dockerfile: client-frontend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./client-frontend:/app
      - /app/node_modules

